name: Release
on:
  release:
    types: [published]

jobs:
  release_to_npm:
    name: Release to npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm build
        env:
          NODE_OPTIONS: --max_old_space_size=4096
      - run: pnpm test
      - run: pnpm lint
      - run: echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: git update-index --assume-unchanged .npmrc
      - run: npx lerna publish from-package --yes
      - if: always()
        run: rm .npmrc
